# Generated by Django 5.2.9 on 2025-12-07 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='date')),
                ('new_users', models.PositiveIntegerField(default=0, verbose_name='new users')),
                ('active_users', models.PositiveIntegerField(default=0, verbose_name='active users')),
                ('new_candidates', models.PositiveIntegerField(default=0, verbose_name='new candidates')),
                ('new_employers', models.PositiveIntegerField(default=0, verbose_name='new employers')),
                ('new_jobs', models.PositiveIntegerField(default=0, verbose_name='new jobs')),
                ('active_jobs', models.PositiveIntegerField(default=0, verbose_name='active jobs')),
                ('total_job_views', models.PositiveIntegerField(default=0, verbose_name='total job views')),
                ('unique_job_viewers', models.PositiveIntegerField(default=0, verbose_name='unique job viewers')),
                ('new_applications', models.PositiveIntegerField(default=0, verbose_name='new applications')),
                ('total_applications', models.PositiveIntegerField(default=0, verbose_name='total applications')),
                ('application_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='application rate %')),
                ('new_companies', models.PositiveIntegerField(default=0, verbose_name='new companies')),
                ('active_companies', models.PositiveIntegerField(default=0, verbose_name='active companies')),
                ('total_searches', models.PositiveIntegerField(default=0, verbose_name='total searches')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='total messages')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='total reviews')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='revenue')),
                ('transactions', models.PositiveIntegerField(default=0, verbose_name='transactions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'daily statistics',
                'verbose_name_plural': 'daily statistics',
                'db_table': 'daily_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFunnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='impressions')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('apply_button_clicks', models.PositiveIntegerField(default=0, verbose_name='apply clicks')),
                ('applications_submitted', models.PositiveIntegerField(default=0, verbose_name='applications')),
                ('view_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='view rate %')),
                ('click_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='click rate %')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='conversion rate %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_stats', to='jobs.job')),
            ],
            options={
                'verbose_name': 'application funnel',
                'verbose_name_plural': 'application funnels',
                'db_table': 'application_funnels',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['job', '-date'], name='application_job_id_0d6392_idx')],
                'unique_together': {('job', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CompanyProfileView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='session ID')),
                ('device_type', models.CharField(default='DESKTOP', max_length=20, verbose_name='device type')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='referrer')),
                ('source', models.CharField(default='DIRECT', max_length=50, verbose_name='source')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='companies.company')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_profile_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company profile view',
                'verbose_name_plural': 'company profile views',
                'db_table': 'company_profile_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['company', '-viewed_at'], name='company_pro_company_0bf3ad_idx'), models.Index(fields=['viewer', '-viewed_at'], name='company_pro_viewer__8aa559_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.CharField(db_index=True, max_length=500, verbose_name='query text')),
                ('search_type', models.CharField(choices=[('JOB', 'Job Search'), ('COMPANY', 'Company Search'), ('CANDIDATE', 'Candidate Search'), ('SKILL', 'Skill Search')], max_length=20, verbose_name='search type')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filters')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='results count')),
                ('clicked_result_id', models.UUIDField(blank=True, null=True, verbose_name='clicked result ID')),
                ('clicked_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='clicked position')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='session ID')),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'search query',
                'verbose_name_plural': 'search queries',
                'db_table': 'search_queries',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['query_text', '-searched_at'], name='search_quer_query_t_1db240_idx'), models.Index(fields=['search_type', '-searched_at'], name='search_quer_search__10b72b_idx'), models.Index(fields=['user', '-searched_at'], name='search_quer_user_id_bc0dc1_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('JOB_VIEW', 'Job View'), ('JOB_APPLY', 'Job Apply'), ('JOB_SAVE', 'Job Save'), ('COMPANY_VIEW', 'Company View'), ('COMPANY_FOLLOW', 'Company Follow'), ('PROFILE_UPDATE', 'Profile Update'), ('RESUME_UPLOAD', 'Resume Upload'), ('MESSAGE_SENT', 'Message Sent'), ('SEARCH', 'Search'), ('REVIEW_POST', 'Review Posted'), ('OTHER', 'Other')], db_index=True, max_length=50, verbose_name='activity type')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user activity',
                'verbose_name_plural': 'user activities',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type', '-created_at'], name='user_activi_user_id_922223_idx'), models.Index(fields=['content_type', 'object_id'], name='user_activi_content_d25f4a_idx')],
            },
        ),
    ]
