# Generated by Django 5.2.9 on 2025-12-07 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='resume file')),
                ('file_name', models.CharField(max_length=255, verbose_name='file name')),
                ('file_size', models.PositiveIntegerField(verbose_name='file size (bytes)')),
                ('file_type', models.CharField(max_length=50, verbose_name='file type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='raw parsed data')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='full name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('summary', models.TextField(blank=True, verbose_name='professional summary')),
                ('headline', models.CharField(blank=True, max_length=500, verbose_name='headline')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='skills')),
                ('work_experience', models.JSONField(blank=True, default=list, verbose_name='work experience')),
                ('education', models.JSONField(blank=True, default=list, verbose_name='education')),
                ('certifications', models.JSONField(blank=True, default=list, verbose_name='certifications')),
                ('languages', models.JSONField(blank=True, default=list, verbose_name='languages')),
                ('total_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='total experience (years)')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='portfolio URL')),
                ('parsing_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='0-100% confidence in parsing accuracy', max_digits=5, null=True, verbose_name='parsing confidence')),
                ('applied_to_profile', models.BooleanField(default=False, verbose_name='applied to profile')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='applied at')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='processing started at')),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='processing completed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'parsed resume',
                'verbose_name_plural': 'parsed resumes',
                'db_table': 'parsed_resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeParsingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(max_length=100, verbose_name='parsing step')),
                ('message', models.TextField(verbose_name='log message')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20, verbose_name='log level')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='additional data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('parsed_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='resume_parser.parsedresume')),
            ],
            options={
                'verbose_name': 'resume parsing log',
                'verbose_name_plural': 'resume parsing logs',
                'db_table': 'resume_parsing_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='parsedresume',
            index=models.Index(fields=['user', '-created_at'], name='parsed_resu_user_id_70a1be_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedresume',
            index=models.Index(fields=['status', '-created_at'], name='parsed_resu_status_25ea1f_idx'),
        ),
    ]
