# Generated by Django 5.2.9 on 2025-12-08 08:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('resume_parser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('llm_provider', models.CharField(choices=[('OPENAI', 'OpenAI ChatGPT'), ('GEMINI', 'Google Gemini'), ('CLAUDE', 'Anthropic Claude')], default='OPENAI', max_length=20, verbose_name='LLM provider')),
                ('model_version', models.CharField(help_text='e.g., gpt-4o, gemini-1.5-pro', max_length=50, verbose_name='model version')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, help_text='0-100 score of CV-JD match quality', max_digits=5, null=True, verbose_name='overall match score')),
                ('strengths', models.JSONField(default=list, help_text='List of candidate strengths identified by LLM', verbose_name='strengths')),
                ('weaknesses', models.JSONField(default=list, help_text='List of gaps or concerns identified by LLM', verbose_name='weaknesses')),
                ('skills_match', models.JSONField(default=dict, help_text='{"matched": [...], "missing": [...], "similar": [...]}', verbose_name='skills match analysis')),
                ('experience_match', models.JSONField(default=dict, help_text='Years, seniority, relevance analysis', verbose_name='experience match analysis')),
                ('interview_questions', models.JSONField(default=list, help_text='AI-generated questions to ask based on CV', verbose_name='suggested interview questions')),
                ('hiring_recommendation', models.TextField(blank=True, help_text='LLM summary: should we proceed with this candidate?', verbose_name='hiring recommendation')),
                ('red_flags', models.JSONField(default=list, help_text='Concerns that recruiter should investigate', verbose_name='red flags')),
                ('technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='technical skills score')),
                ('experience_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='experience score')),
                ('education_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='education score')),
                ('culture_fit_score', models.DecimalField(blank=True, decimal_places=2, help_text='Based on job description values/culture section', max_digits=5, null=True, verbose_name='culture fit score')),
                ('raw_llm_response', models.TextField(blank=True, help_text='Complete LLM output for debugging', verbose_name='raw LLM response')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='prompt tokens')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='completion tokens')),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Cost of LLM API call', max_digits=10, verbose_name='analysis cost (USD)')),
                ('analysis_duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='analysis duration (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_analyses_requested', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, help_text='Job to match against (optional - can analyze CV standalone)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_analyses', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_analyses', to='resume_parser.parsedresume')),
            ],
            options={
                'verbose_name': 'CV analysis',
                'verbose_name_plural': 'CV analyses',
                'db_table': 'cv_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVAnalysisCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cv_content_hash', models.CharField(help_text='SHA256 hash of CV text to detect changes', max_length=64, verbose_name='CV content hash')),
                ('jd_content_hash', models.CharField(blank=True, help_text='SHA256 hash of job description', max_length=64, null=True, verbose_name='JD content hash')),
                ('cache_hits', models.PositiveIntegerField(default=0, verbose_name='cache hits')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='last accessed')),
                ('expires_at', models.DateTimeField(help_text='Cache expiration (30 days default)', verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cache_entry', to='resume_parser.cvanalysis')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume_parser.parsedresume')),
            ],
            options={
                'verbose_name': 'CV analysis cache',
                'verbose_name_plural': 'CV analysis cache',
                'db_table': 'cv_analysis_cache',
            },
        ),
        migrations.CreateModel(
            name='LLMPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., "Technical Role Analysis", "Executive Screening"', max_length=200, unique=True, verbose_name='template name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('system_prompt', models.TextField(help_text='System role instructions for LLM', verbose_name='system prompt')),
                ('user_prompt_template', models.TextField(help_text='Template with variables: {cv_text}, {job_description}, {job_title}, etc.', verbose_name='user prompt template')),
                ('response_format', models.JSONField(default=dict, help_text='JSON schema for structured output', verbose_name='expected response format')),
                ('temperature', models.DecimalField(decimal_places=2, default=Decimal('0.3'), help_text='0.0-1.0, lower = more deterministic', max_digits=3, verbose_name='temperature')),
                ('max_tokens', models.PositiveIntegerField(default=2000, help_text='Maximum response length', verbose_name='max tokens')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default', models.BooleanField(default=False, verbose_name='default template')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='usage count')),
                ('avg_score', models.DecimalField(blank=True, decimal_places=2, help_text='Track if template is too harsh/lenient', max_digits=5, null=True, verbose_name='average score produced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM prompt template',
                'verbose_name_plural': 'LLM prompt templates',
                'db_table': 'llm_prompt_templates',
                'ordering': ['-is_default', '-usage_count', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='cvanalysis',
            index=models.Index(fields=['resume', '-created_at'], name='cv_analyses_resume__622ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='cvanalysis',
            index=models.Index(fields=['job', '-overall_score'], name='cv_analyses_job_id_bc2faf_idx'),
        ),
        migrations.AddIndex(
            model_name='cvanalysis',
            index=models.Index(fields=['-overall_score'], name='cv_analyses_overall_5c1366_idx'),
        ),
        migrations.AddIndex(
            model_name='cvanalysiscache',
            index=models.Index(fields=['resume', 'job'], name='cv_analysis_resume__b247b9_idx'),
        ),
        migrations.AddIndex(
            model_name='cvanalysiscache',
            index=models.Index(fields=['expires_at'], name='cv_analysis_expires_086a29_idx'),
        ),
        migrations.AddIndex(
            model_name='cvanalysiscache',
            index=models.Index(fields=['cv_content_hash', 'jd_content_hash'], name='cv_analysis_cv_cont_53ec7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cvanalysiscache',
            unique_together={('cv_content_hash', 'jd_content_hash')},
        ),
    ]
