# Generated by Django 5.2.9 on 2025-12-07 19:10

import apps.files.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.files.models.user_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif', 'txt'])], verbose_name='file')),
                ('file_type', models.CharField(choices=[('RESUME', 'Resume/CV'), ('COVER_LETTER', 'Cover Letter'), ('PORTFOLIO', 'Portfolio'), ('COMPANY_LOGO', 'Company Logo'), ('COMPANY_COVER', 'Company Cover Image'), ('PROFILE_PICTURE', 'Profile Picture'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], max_length=20, verbose_name='file type')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original filename')),
                ('file_size', models.PositiveIntegerField(verbose_name='file size (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('is_processed', models.BooleanField(default=False, verbose_name='processed')),
                ('parsed_data', models.JSONField(blank=True, null=True, verbose_name='parsed data')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uploaded file',
                'verbose_name_plural': 'uploaded files',
                'db_table': 'uploaded_files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['uploaded_by', 'file_type'], name='uploaded_fi_uploade_464720_idx'), models.Index(fields=['uploaded_at'], name='uploaded_fi_uploade_ab87d6_idx')],
            },
        ),
    ]
