# Generated by Django 5.2.9 on 2025-12-07 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_on_application', models.BooleanField(default=True, verbose_name='email on application')),
                ('email_on_interview', models.BooleanField(default=True, verbose_name='email on interview')),
                ('email_on_message', models.BooleanField(default=True, verbose_name='email on message')),
                ('email_on_job_match', models.BooleanField(default=True, verbose_name='email on job match')),
                ('email_on_company_update', models.BooleanField(default=False, verbose_name='email on company update')),
                ('push_on_application', models.BooleanField(default=True, verbose_name='push on application')),
                ('push_on_interview', models.BooleanField(default=True, verbose_name='push on interview')),
                ('push_on_message', models.BooleanField(default=True, verbose_name='push on message')),
                ('daily_digest', models.BooleanField(default=False, verbose_name='daily digest')),
                ('weekly_digest', models.BooleanField(default=True, verbose_name='weekly digest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('APPLICATION_RECEIVED', 'Application Received'), ('APPLICATION_REVIEWED', 'Application Reviewed'), ('APPLICATION_ACCEPTED', 'Application Accepted'), ('APPLICATION_REJECTED', 'Application Rejected'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_REMINDER', 'Interview Reminder'), ('INTERVIEW_CANCELLED', 'Interview Cancelled'), ('JOB_POSTED', 'Job Posted'), ('JOB_EXPIRED', 'Job Expired'), ('JOB_MATCH', 'Job Match Found'), ('NEW_JOB_ALERT', 'New Job Alert'), ('COMPANY_FOLLOWED', 'Company Followed'), ('COMPANY_UPDATE', 'Company Update'), ('NEW_COMPANY_JOB', 'New Job from Followed Company'), ('NEW_MESSAGE', 'New Message'), ('MESSAGE_REPLY', 'Message Reply'), ('NEW_REVIEW', 'New Review'), ('REVIEW_REPLY', 'Review Reply'), ('SYSTEM_ALERT', 'System Alert'), ('ACCOUNT_UPDATE', 'Account Update')], max_length=30, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='action URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10, verbose_name='priority')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_2c3905_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx')],
            },
        ),
    ]
