# Generated by Django 5.2.9 on 2025-12-08 08:42

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_matching', '0001_install_pgvector'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, help_text='SHA256 hash of text + provider + model', max_length=64, unique=True, verbose_name='cache key')),
                ('embedding_vector', pgvector.django.vector.VectorField(dimensions=1536, help_text='Cached embedding vector')),
                ('provider', models.CharField(choices=[('OPENAI', 'OpenAI (text-embedding-3-small)'), ('OPENAI_LARGE', 'OpenAI (text-embedding-3-large)'), ('SENTENCE_BERT', 'Sentence-BERT'), ('COHERE', 'Cohere'), ('CUSTOM', 'Custom Model')], max_length=20, verbose_name='provider')),
                ('model_version', models.CharField(max_length=100, verbose_name='model version')),
                ('dimension', models.PositiveIntegerField(verbose_name='dimensions')),
                ('hit_count', models.PositiveIntegerField(default=0, help_text='Number of times this cache entry was used', verbose_name='cache hits')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='last accessed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'embedding cache',
                'verbose_name_plural': 'embedding cache',
                'db_table': 'embedding_cache',
                'indexes': [models.Index(fields=['-hit_count'], name='embedding_c_hit_cou_d18638_idx'), models.Index(fields=['-last_accessed_at'], name='embedding_c_last_ac_02bad7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Vector representation of candidate profile + skills + experience', null=True)),
                ('provider', models.CharField(choices=[('OPENAI', 'OpenAI (text-embedding-3-small)'), ('OPENAI_LARGE', 'OpenAI (text-embedding-3-large)'), ('SENTENCE_BERT', 'Sentence-BERT'), ('COHERE', 'Cohere'), ('CUSTOM', 'Custom Model')], default='OPENAI', max_length=20, verbose_name='embedding provider')),
                ('model_version', models.CharField(default='text-embedding-3-small', max_length=100, verbose_name='model version')),
                ('dimension', models.PositiveIntegerField(default=1536, verbose_name='vector dimensions')),
                ('source_text', models.TextField(help_text='Combined text from profile, skills, experience, education', verbose_name='source text')),
                ('is_stale', models.BooleanField(default=False, help_text='True if profile changed, needs regeneration', verbose_name='stale')),
                ('last_embedded_at', models.DateTimeField(blank=True, null=True, verbose_name='last embedded')),
                ('embedding_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='embedding cost (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidate embedding',
                'verbose_name_plural': 'candidate embeddings',
                'db_table': 'candidate_embeddings',
                'indexes': [models.Index(fields=['is_stale', '-created_at'], name='candidate_e_is_stal_6e2dad_idx'), models.Index(fields=['provider', 'model_version'], name='candidate_e_provide_af758f_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('embedding_vector', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Vector representation of job description + requirements', null=True)),
                ('provider', models.CharField(choices=[('OPENAI', 'OpenAI (text-embedding-3-small)'), ('OPENAI_LARGE', 'OpenAI (text-embedding-3-large)'), ('SENTENCE_BERT', 'Sentence-BERT'), ('COHERE', 'Cohere'), ('CUSTOM', 'Custom Model')], default='OPENAI', max_length=20, verbose_name='embedding provider')),
                ('model_version', models.CharField(default='text-embedding-3-small', help_text='e.g., text-embedding-3-small, all-MiniLM-L6-v2', max_length=100, verbose_name='model version')),
                ('dimension', models.PositiveIntegerField(default=1536, verbose_name='vector dimensions')),
                ('source_text', models.TextField(help_text='Combined text used to generate embedding (job title + description + requirements + skills)', verbose_name='source text')),
                ('is_stale', models.BooleanField(default=False, help_text='True if job content changed, embedding needs regeneration', verbose_name='stale')),
                ('last_embedded_at', models.DateTimeField(blank=True, null=True, verbose_name='last embedded')),
                ('embedding_cost', models.DecimalField(blank=True, decimal_places=6, help_text='Cost to generate this embedding', max_digits=10, null=True, verbose_name='embedding cost (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='jobs.job')),
            ],
            options={
                'verbose_name': 'job embedding',
                'verbose_name_plural': 'job embeddings',
                'db_table': 'job_embeddings',
                'indexes': [models.Index(fields=['is_stale', '-created_at'], name='job_embeddi_is_stal_fbdcbd_idx'), models.Index(fields=['provider', 'model_version'], name='job_embeddi_provide_1da032_idx')],
            },
        ),
        migrations.CreateModel(
            name='SemanticMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField(db_index=True, help_text='Cosine similarity (0.0 = no match, 1.0 = perfect match)', verbose_name='similarity score')),
                ('match_quality', models.CharField(choices=[('EXCELLENT', 'Excellent Match (90-100%)'), ('GOOD', 'Good Match (75-89%)'), ('MODERATE', 'Moderate Match (60-74%)'), ('LOW', 'Low Match (40-59%)'), ('POOR', 'Poor Match (<40%)')], db_index=True, max_length=20, verbose_name='match quality')),
                ('match_reasons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, help_text='List of reasons why candidate matches (e.g., "5+ years Python experience")', null=True, size=None)),
                ('skill_overlap', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Skills that overlap between job and candidate', null=True, size=None)),
                ('is_valid', models.BooleanField(default=True, help_text='False if job/candidate embedding changed, needs recalculation', verbose_name='valid')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Cache expiration (default 7 days)', null=True, verbose_name='expires at')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_matches', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_matches', to='jobs.job')),
            ],
            options={
                'verbose_name': 'semantic match',
                'verbose_name_plural': 'semantic matches',
                'db_table': 'semantic_matches',
                'ordering': ['-similarity_score'],
                'indexes': [models.Index(fields=['job', '-similarity_score'], name='semantic_ma_job_id_003a5a_idx'), models.Index(fields=['candidate', '-similarity_score'], name='semantic_ma_candida_24cd65_idx'), models.Index(fields=['match_quality', '-similarity_score'], name='semantic_ma_match_q_5389bc_idx'), models.Index(fields=['is_valid', '-calculated_at'], name='semantic_ma_is_vali_2bf0b1_idx')],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
