# Generated by Django 5.2.9 on 2025-12-07 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='benefit name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.URLField(blank=True, null=True, verbose_name='icon URL')),
                ('category', models.CharField(choices=[('HEALTH', 'Health & Wellness'), ('FINANCIAL', 'Financial'), ('WORK_LIFE', 'Work-Life Balance'), ('PROFESSIONAL', 'Professional Development'), ('EQUIPMENT', 'Equipment & Tools'), ('OFFICE', 'Office Perks'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='category')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='usage count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'benefit',
                'verbose_name_plural': 'benefits',
                'db_table': 'benefits',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='currency name')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='currency code')),
                ('symbol', models.CharField(max_length=10, verbose_name='symbol')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=15, verbose_name='exchange rate to USD')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
                'db_table': 'currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='degree name')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='short name')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='education level')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'degree',
                'verbose_name_plural': 'degrees',
                'db_table': 'degrees',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='language name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='language code')),
                ('native_name', models.CharField(max_length=100, verbose_name='native name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'db_table': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='industry name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.URLField(blank=True, null=True, verbose_name='icon URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_industries', to='master_data.industry')),
            ],
            options={
                'verbose_name': 'industry',
                'verbose_name_plural': 'industries',
                'db_table': 'industries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='category name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.URLField(blank=True, null=True, verbose_name='icon URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('job_count', models.PositiveIntegerField(default=0, verbose_name='total jobs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='master_data.jobcategory')),
            ],
            options={
                'verbose_name': 'job category',
                'verbose_name_plural': 'job categories',
                'db_table': 'job_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='category name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='master_data.skillcategory')),
            ],
            options={
                'verbose_name': 'skill category',
                'verbose_name_plural': 'skill categories',
                'db_table': 'skill_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='tag name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('tag_type', models.CharField(choices=[('GENERAL', 'General'), ('JOB', 'Job'), ('COMPANY', 'Company'), ('SKILL', 'Skill')], default='GENERAL', max_length=20, verbose_name='tag type')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='usage count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'db_table': 'tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tag_type', 'is_active'], name='tags_tag_typ_e4b2db_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='location name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('location_type', models.CharField(choices=[('COUNTRY', 'Country'), ('PROVINCE', 'Province/State'), ('CITY', 'City'), ('DISTRICT', 'District')], max_length=20, verbose_name='type')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='country code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('job_count', models.PositiveIntegerField(default=0, verbose_name='total jobs')),
                ('company_count', models.PositiveIntegerField(default=0, verbose_name='total companies')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_locations', to='master_data.location')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'db_table': 'locations',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['location_type', 'is_active'], name='locations_locatio_439c44_idx'), models.Index(fields=['country_code'], name='locations_country_e8a377_idx')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='skill name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('skill_type', models.CharField(choices=[('TECHNICAL', 'Technical'), ('SOFT', 'Soft Skill'), ('LANGUAGE', 'Language'), ('CERTIFICATION', 'Certification'), ('TOOL', 'Tool/Software')], default='TECHNICAL', max_length=20, verbose_name='skill type')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='aliases')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='usage count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='master_data.skillcategory')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'db_table': 'skills',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['skill_type', 'is_active'], name='skills_skill_t_795408_idx')],
            },
        ),
    ]
