# Generated by Django 5.2.9 on 2025-12-07 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('JOB', 'Job Recommendation'), ('CANDIDATE', 'Candidate Recommendation')], max_length=20, verbose_name='recommendation type')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='rating')),
                ('feedback_text', models.TextField(blank=True, verbose_name='feedback')),
                ('helpful_factors', models.JSONField(blank=True, default=list, help_text='Factors that made recommendation useful', verbose_name='helpful factors')),
                ('unhelpful_factors', models.JSONField(blank=True, default=list, help_text='Factors that made recommendation not useful', verbose_name='unhelpful factors')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recommendation feedback',
                'verbose_name_plural': 'recommendation feedback',
                'db_table': 'recommendation_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.DecimalField(decimal_places=2, help_text='Overall matching score (0-100)', max_digits=5, verbose_name='match score')),
                ('skills_match', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='skills match')),
                ('experience_match', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='experience match')),
                ('match_details', models.JSONField(blank=True, default=dict, verbose_name='match details')),
                ('viewed', models.BooleanField(default=False, verbose_name='viewed')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='viewed at')),
                ('contacted', models.BooleanField(default=False, verbose_name='contacted')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='contacted at')),
                ('shortlisted', models.BooleanField(default=False, verbose_name='shortlisted')),
                ('shortlisted_at', models.DateTimeField(blank=True, null=True, verbose_name='shortlisted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for_jobs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_recommendations', to='jobs.job')),
            ],
            options={
                'verbose_name': 'candidate recommendation',
                'verbose_name_plural': 'candidate recommendations',
                'db_table': 'candidate_recommendations',
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['job', '-match_score', '-created_at'], name='candidate_r_job_id_dfdae7_idx'), models.Index(fields=['candidate', '-match_score'], name='candidate_r_candida_71ebe3_idx')],
                'unique_together': {('job', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.DecimalField(decimal_places=2, help_text='Overall matching score (0-100)', max_digits=5, verbose_name='match score')),
                ('skills_match', models.DecimalField(decimal_places=2, default=0, help_text='Skills matching score (0-100)', max_digits=5, verbose_name='skills match')),
                ('experience_match', models.DecimalField(decimal_places=2, default=0, help_text='Experience matching score (0-100)', max_digits=5, verbose_name='experience match')),
                ('location_match', models.DecimalField(decimal_places=2, default=0, help_text='Location matching score (0-100)', max_digits=5, verbose_name='location match')),
                ('salary_match', models.DecimalField(decimal_places=2, default=0, help_text='Salary matching score (0-100)', max_digits=5, verbose_name='salary match')),
                ('match_details', models.JSONField(blank=True, default=dict, help_text='Detailed matching information', verbose_name='match details')),
                ('viewed', models.BooleanField(default=False, verbose_name='viewed')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='viewed at')),
                ('clicked', models.BooleanField(default=False, verbose_name='clicked')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='clicked at')),
                ('applied', models.BooleanField(default=False, verbose_name='applied')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='applied at')),
                ('dismissed', models.BooleanField(default=False, verbose_name='dismissed')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='dismissed at')),
                ('feedback_rating', models.PositiveSmallIntegerField(blank=True, help_text='User feedback on recommendation quality (1-5)', null=True, verbose_name='feedback rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job recommendation',
                'verbose_name_plural': 'job recommendations',
                'db_table': 'job_recommendations',
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['user', '-match_score', '-created_at'], name='job_recomme_user_id_6cae37_idx'), models.Index(fields=['job', '-match_score'], name='job_recomme_job_id_0ec05d_idx'), models.Index(fields=['user', 'viewed', '-created_at'], name='job_recomme_user_id_e56fab_idx')],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
