"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config, Csv
import os
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==============================================================================
# SECURITY SETTINGS
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

# Security Settings from environment
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', cast=bool)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', cast=bool)
X_FRAME_OPTIONS = config('X_FRAME_OPTIONS')
SECURE_CONTENT_TYPE_NOSNIFF = config('SECURE_CONTENT_TYPE_NOSNIFF', cast=bool)
SECURE_BROWSER_XSS_FILTER = config('SECURE_BROWSER_XSS_FILTER', cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if config('SECURE_PROXY_SSL_HEADER_ENABLED', cast=bool) else None

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    'django_celery_beat',
    'django_celery_results',
    'channels',
    
    # Local apps - Core
    'apps.authentication',
    'apps.companies',
    'apps.jobs',
    'apps.applications',
    'apps.master_data',
    'apps.files',
    
    # Local apps - Features
    'apps.notifications',
    'apps.payments',
    'apps.analytics',
    'apps.messaging',
    'apps.reviews',
    'apps.saved_jobs',
    'apps.recommendations',
    
    # Local apps - Integration
    'apps.search',
    'apps.storage',
    'apps.email_service',
    'apps.export',
    'apps.resume_parser',
    
    # Local apps - Admin & Monitoring
    'apps.audit_logs',
    'apps.reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Custom User Model
AUTH_USER_MODEL = 'authentication.User'


# ==============================================================================
# DATABASE CONFIGURATION
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', cast=int),
        'CONN_HEALTH_CHECKS': config('DB_CONN_HEALTH_CHECKS', cast=bool),
        'OPTIONS': {
            'sslmode': 'require',
        } if 'aivencloud.com' in config('DB_HOST') else {},
    }
}


# ==============================================================================
# PASSWORD VALIDATION
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# ==============================================================================
# STATIC FILES & MEDIA
# ==============================================================================

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# REST FRAMEWORK CONFIGURATION
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': config('API_PAGE_SIZE', cast=int),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': config('API_RATE_LIMIT_ANON'),
        'user': config('API_RATE_LIMIT_USER'),
    },
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
}


# ==============================================================================
# JWT CONFIGURATION
# ==============================================================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=config('JWT_ACCESS_TOKEN_LIFETIME_HOURS', cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_TOKEN_LIFETIME_DAYS', cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': config('JWT_ALGORITHM'),
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=config('JWT_SLIDING_TOKEN_REFRESH_LIFETIME_DAYS', cast=int)),
    'SLIDING_TOKEN_LIFETIME': timedelta(days=config('JWT_SLIDING_TOKEN_LIFETIME_DAYS', cast=int)),
}


# ==============================================================================
# CORS CONFIGURATION
# ==============================================================================

CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv())

# Validate CORS in production
if not DEBUG and CORS_ALLOWED_ORIGINS:
    for origin in CORS_ALLOWED_ORIGINS:
        if 'localhost' in origin or '127.0.0.1' in origin:
            import warnings
            warnings.warn(
                f"⚠️  PRODUCTION WARNING: CORS contains localhost origin: {origin}\n"
                "This is a security risk! Update CORS_ALLOWED_ORIGINS in .env to only include production domains.",
                RuntimeWarning
            )

CORS_ALLOW_CREDENTIALS = config('CORS_ALLOW_CREDENTIALS', cast=bool)

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv())


# ==============================================================================
# CELERY CONFIGURATION
# ==============================================================================

CELERY_BROKER_URL = config('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_ALWAYS_EAGER = config('CELERY_TASK_ALWAYS_EAGER', cast=bool)
CELERY_TASK_EAGER_PROPAGATES = config('CELERY_TASK_EAGER_PROPAGATES', cast=bool)
CELERY_WORKER_CONCURRENCY = config('CELERY_WORKER_CONCURRENCY', cast=int)
CELERY_WORKER_PREFETCH_MULTIPLIER = config('CELERY_WORKER_PREFETCH_MULTIPLIER', cast=int)

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    # Job View Tracking
    'bulk-sync-job-views': {
        'task': 'apps.jobs.tasks.bulk_sync_job_views',
        'schedule': 3600.0,  # Every hour
    },
    'cleanup-old-job-views': {
        'task': 'apps.jobs.tasks.cleanup_old_job_views',
        'schedule': 30 * 24 * 3600.0,  # Every 30 days
        'kwargs': {'days': 90}
    },
    'update-job-stats': {
        'task': 'apps.jobs.tasks.update_job_stats',
        'schedule': 24 * 3600.0,  # Every day
    },
    
    # CRITICAL: Subscription Management
    'expire-subscriptions': {
        'task': 'apps.payments.tasks.expire_subscriptions',
        'schedule': 3600.0,  # Every hour - MUST run regularly!
    },
    'process-auto-renewals': {
        'task': 'apps.payments.tasks.process_auto_renewals',
        'schedule': 24 * 3600.0,  # Every day
    },
    'send-renewal-reminders': {
        'task': 'apps.payments.tasks.send_renewal_reminders',
        'schedule': 24 * 3600.0,  # Every day at midnight
    },
    'cleanup-pending-payments': {
        'task': 'apps.payments.tasks.cleanup_pending_payments',
        'schedule': 24 * 3600.0,  # Every day
    },
    
    # Monthly Tasks
    'generate-monthly-invoices': {
        'task': 'apps.payments.tasks.generate_monthly_invoices',
        'schedule': 30 * 24 * 3600.0,  # Every 30 days
    },
    
    # Resume Parser Cleanup Tasks
    'cleanup-temp-resume-files': {
        'task': 'apps.resume_parser.tasks_cleanup.cleanup_temp_resume_files',
        'schedule': 3600.0,  # Every hour - clean files >1 hour old
    },
    'cleanup-old-parsed-resumes': {
        'task': 'apps.resume_parser.tasks_cleanup.cleanup_old_parsed_resumes',
        'schedule': 24 * 3600.0,  # Daily - delete failed records >30 days
    },
    'optimize-resume-storage': {
        'task': 'apps.resume_parser.tasks_cleanup.optimize_resume_storage',
        'schedule': 7 * 24 * 3600.0,  # Weekly - compress old resumes
    },
    
    # Elasticsearch Maintenance
    'bulk-reindex-jobs': {
        'task': 'apps.search.tasks.bulk_reindex_jobs',
        'schedule': 7 * 24 * 3600.0,  # Weekly - full job reindex
    },
    'bulk-reindex-companies': {
        'task': 'apps.search.tasks.bulk_reindex_companies',
        'schedule': 7 * 24 * 3600.0,  # Weekly - full company reindex
    },
}


# ==============================================================================
# CHANNELS CONFIGURATION (WebSocket)
# ==============================================================================

ASGI_APPLICATION = 'backend.asgi.application'

REDIS_URL = config('REDIS_URL')

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    },
}


# ==============================================================================
# CACHE CONFIGURATION
# ==============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config('CACHE_REDIS_URL'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'recruitment',
        'TIMEOUT': 300,
    }
}

CACHE_TTL = 60 * 5  # 5 minutes


# ==============================================================================
# ELASTICSEARCH CONFIGURATION
# ==============================================================================

ELASTICSEARCH_DSL = {
    'default': {
        'hosts': config('ELASTICSEARCH_HOST'),
        'http_auth': (
            config('ELASTICSEARCH_USERNAME'),
            config('ELASTICSEARCH_PASSWORD')
        ) if config('ELASTICSEARCH_USERNAME') else None,
        'use_ssl': config('ELASTICSEARCH_USE_SSL', cast=bool),
        'verify_certs': config('ELASTICSEARCH_VERIFY_CERTS', cast=bool),
    },
}

# ==============================================================================
# AWS S3 / MinIO CONFIGURATION
# ==============================================================================

USE_S3 = config('USE_S3', cast=bool)

AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME')
AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_VERIFY = config('AWS_S3_USE_SSL', cast=bool)

# File Upload Settings
MAX_UPLOAD_SIZE = config('MAX_UPLOAD_SIZE', cast=int)
ALLOWED_CV_EXTENSIONS = config('ALLOWED_CV_EXTENSIONS', cast=Csv())
ALLOWED_IMAGE_EXTENSIONS = config('ALLOWED_IMAGE_EXTENSIONS', cast=Csv())


# ==============================================================================
# EMAIL CONFIGURATION
# ==============================================================================

EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
EMAIL_TIMEOUT = 10


# ==============================================================================
# API DOCUMENTATION (Swagger/OpenAPI)
# ==============================================================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'Recruitment Platform API',
    'DESCRIPTION': 'API for job posting, candidate matching, and recruitment management',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_NAME_OVERRIDES': {
        'ApplicationStatusEnum': 'apps.applications.models.ApplicationStatus.choices',
        'JobStatusEnum': 'apps.jobs.models.JobStatus.choices',
        'JobTypeEnum': 'apps.jobs.models.JobType.choices',
        'ExperienceLevelEnum': 'apps.jobs.models.ExperienceLevel.choices',
        'CompanySizeEnum': 'apps.companies.models.CompanySize.choices',
        'UserRoleEnum': 'apps.authentication.models.UserRole.choices',
    },
}


# ==============================================================================
# LOGGING CONFIGURATION
# ==============================================================================

LOGS_DIR = BASE_DIR / 'logs'
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


# ==============================================================================
# SESSION SETTINGS
# ==============================================================================

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', cast=int)
SESSION_COOKIE_NAME = config('SESSION_COOKIE_NAME')
SESSION_COOKIE_DOMAIN = config('SESSION_COOKIE_DOMAIN')


# ==============================================================================
# PAYMENT GATEWAY SETTINGS
# ==============================================================================

# VNPay Configuration
VNPAY_TMN_CODE = config('VNPAY_TMN_CODE')
VNPAY_HASH_SECRET = config('VNPAY_HASH_SECRET')
VNPAY_URL = config('VNPAY_URL')
VNPAY_RETURN_URL = config('VNPAY_RETURN_URL')
VNPAY_API_URL = config('VNPAY_API_URL')

# Stripe Configuration
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET')


# ==============================================================================
# AI/ML SERVICES
# ==============================================================================

# OpenAI Configuration
OPENAI_API_KEY = config('OPENAI_API_KEY')
OPENAI_MODEL = config('OPENAI_MODEL')
OPENAI_MAX_TOKENS = config('OPENAI_MAX_TOKENS', cast=int)
OPENAI_TEMPERATURE = config('OPENAI_TEMPERATURE', cast=float)

# Resume Parser Configuration
RESUME_PARSER_API_KEY = config('RESUME_PARSER_API_KEY')
RESUME_PARSER_ENDPOINT = config('RESUME_PARSER_ENDPOINT')


# ==============================================================================
# NOTIFICATION SERVICES
# ==============================================================================

# OneSignal Configuration
ONESIGNAL_APP_ID = config('ONESIGNAL_APP_ID')
ONESIGNAL_REST_API_KEY = config('ONESIGNAL_REST_API_KEY')
ONESIGNAL_USER_AUTH_KEY = config('ONESIGNAL_USER_AUTH_KEY')

# Firebase Configuration
# FIREBASE_CREDENTIALS = config('FIREBASE_CREDENTIALS')
# FIREBASE_DATABASE_URL = config('FIREBASE_DATABASE_URL')


# ==============================================================================
# SOCIAL AUTHENTICATION
# ==============================================================================

# # Google OAuth
# GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID')
# GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET')

# # Facebook OAuth
# FACEBOOK_APP_ID = config('FACEBOOK_APP_ID')
# FACEBOOK_APP_SECRET = config('FACEBOOK_APP_SECRET')

# # LinkedIn OAuth
# LINKEDIN_CLIENT_ID = config('LINKEDIN_CLIENT_ID')
# LINKEDIN_CLIENT_SECRET = config('LINKEDIN_CLIENT_SECRET')


# ==============================================================================
# FEATURE FLAGS
# ==============================================================================

ENABLE_AI_JOB_MATCHING = config('ENABLE_AI_JOB_MATCHING', cast=bool)
ENABLE_RESUME_PARSING = config('ENABLE_RESUME_PARSING', cast=bool)
ENABLE_EMAIL_NOTIFICATIONS = config('ENABLE_EMAIL_NOTIFICATIONS', cast=bool)
ENABLE_PUSH_NOTIFICATIONS = config('ENABLE_PUSH_NOTIFICATIONS', cast=bool)
ENABLE_SOCIAL_LOGIN = config('ENABLE_SOCIAL_LOGIN', cast=bool)
ENABLE_PAYMENT_GATEWAY = config('ENABLE_PAYMENT_GATEWAY', cast=bool)
ENABLE_ELASTICSEARCH = config('ENABLE_ELASTICSEARCH', cast=bool)
ENABLE_AUDIT_LOGGING = config('ENABLE_AUDIT_LOGGING', cast=bool)


# ==============================================================================
# BUSINESS LOGIC SETTINGS
# ==============================================================================

# Job Application Settings
MAX_APPLICATIONS_PER_DAY = config('MAX_APPLICATIONS_PER_DAY', cast=int)
APPLICATION_EXPIRY_DAYS = config('APPLICATION_EXPIRY_DAYS', cast=int)

# CV Storage Settings
CV_STORAGE_LIMIT_MB = config('CV_STORAGE_LIMIT_MB', cast=int)
MAX_CV_PER_USER = config('MAX_CV_PER_USER', cast=int)

# Job Posting Settings
JOB_AUTO_CLOSE_DAYS = config('JOB_AUTO_CLOSE_DAYS', cast=int)
JOB_FEATURED_DURATION_DAYS = config('JOB_FEATURED_DURATION_DAYS', cast=int)

# Search Settings
SEARCH_RESULTS_PER_PAGE = config('SEARCH_RESULTS_PER_PAGE', cast=int)
MAX_SEARCH_RESULTS = config('MAX_SEARCH_RESULTS', cast=int)

# Recommendation Settings
RECOMMENDATION_COUNT = config('RECOMMENDATION_COUNT', cast=int)
RECOMMENDATION_REFRESH_HOURS = config('RECOMMENDATION_REFRESH_HOURS', cast=int)

# Review Settings
MIN_REVIEW_LENGTH = config('MIN_REVIEW_LENGTH', cast=int)
MAX_REVIEW_LENGTH = config('MAX_REVIEW_LENGTH', cast=int)


# ==============================================================================
# EMAIL CONFIGURATION
# ==============================================================================

# Email Backend
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')

# SMTP Settings (for production)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', cast=int, default=587)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool, default=True)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Default email addresses
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@cown.com')
SERVER_EMAIL = config('SERVER_EMAIL', default='server@cown.com')

# Email timeout
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', cast=int, default=30)


# ==============================================================================
# MONITORING & ERROR TRACKING
# ==============================================================================

# Sentry Configuration
if not DEBUG and config('SENTRY_DSN'):
    sentry_sdk.init(
        dsn=config('SENTRY_DSN'),
        integrations=[DjangoIntegration()],
        traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', cast=float),
        send_default_pii=config('SENTRY_SEND_DEFAULT_PII', cast=bool),
        environment=config('SENTRY_ENVIRONMENT'),
    )

