# Generated by Django 5.2.9 on 2025-12-07 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='template name')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='template code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('html_content', models.TextField(verbose_name='HTML content')),
                ('text_content', models.TextField(blank=True, verbose_name='text content')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Available variables for this template', verbose_name='template variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('category', models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('APPLICATION', 'Application'), ('JOB', 'Job'), ('NOTIFICATION', 'Notification'), ('MARKETING', 'Marketing'), ('SYSTEM', 'System')], default='SYSTEM', max_length=50, verbose_name='category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'db_table': 'email_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254, verbose_name='to email')),
                ('cc_emails', models.JSONField(blank=True, default=list, verbose_name='CC emails')),
                ('bcc_emails', models.JSONField(blank=True, default=list, verbose_name='BCC emails')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('html_content', models.TextField(verbose_name='HTML content')),
                ('text_content', models.TextField(blank=True, verbose_name='text content')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='context data')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], db_index=True, default='PENDING', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='opened at')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='clicked at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='retry count')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='max retries')),
                ('provider', models.CharField(choices=[('SMTP', 'SMTP'), ('SENDGRID', 'SendGrid'), ('AWS_SES', 'AWS SES'), ('MAILGUN', 'Mailgun'), ('CONSOLE', 'Console (Debug)')], default='CONSOLE', max_length=50, verbose_name='email provider')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, verbose_name='provider message ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='email_service.emailtemplate')),
            ],
            options={
                'verbose_name': 'email log',
                'verbose_name_plural': 'email logs',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(choices=[(1, 'Critical'), (3, 'High'), (5, 'Normal'), (7, 'Low')], db_index=True, default=5, verbose_name='priority')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='scheduled at')),
                ('is_processing', models.BooleanField(default=False, verbose_name='is processing')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='email_service.emaillog')),
            ],
            options={
                'verbose_name': 'email queue item',
                'verbose_name_plural': 'email queue',
                'db_table': 'email_queue',
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['priority', 'created_at'], name='email_queue_priorit_277c16_idx'), models.Index(fields=['is_processing', 'scheduled_at'], name='email_queue_is_proc_281b8c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['to_email', '-created_at'], name='email_logs_to_emai_5b10dd_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', '-created_at'], name='email_logs_status_012124_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['user', '-created_at'], name='email_logs_user_id_fdc1a8_idx'),
        ),
    ]
