# Generated by Django 5.2.9 on 2025-12-07 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('DIRECT', 'Direct Message'), ('JOB', 'Job Discussion'), ('APPLICATION', 'Application Discussion'), ('SUPPORT', 'Support Chat')], default='DIRECT', max_length=20, verbose_name='type')),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('is_muted', models.BooleanField(default=False, verbose_name='muted')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='last message at')),
                ('last_message_preview', models.TextField(blank=True, max_length=200, verbose_name='last message preview')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'db_table': 'conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20, verbose_name='role')),
                ('is_muted', models.BooleanField(default=False, verbose_name='muted')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='unread count')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='last read at')),
                ('last_read_message_id', models.UUIDField(blank=True, null=True, verbose_name='last read message')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='notifications enabled')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='left at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_details', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversation participant',
                'verbose_name_plural': 'conversation participants',
                'db_table': 'conversation_participants',
                'ordering': ['-joined_at'],
                'unique_together': {('conversation', 'user')},
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', through='messaging.ConversationParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('FILE', 'File'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('SYSTEM', 'System Message')], default='TEXT', max_length=20, verbose_name='type')),
                ('content', models.TextField(verbose_name='content')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='attachments')),
                ('is_edited', models.BooleanField(default=False, verbose_name='edited')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('reactions', models.JSONField(blank=True, default=dict, verbose_name='reactions')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(verbose_name='file URL')),
                ('file_name', models.CharField(max_length=255, verbose_name='file name')),
                ('file_type', models.CharField(max_length=100, verbose_name='file type')),
                ('file_size', models.BigIntegerField(verbose_name='file size (bytes)')),
                ('thumbnail_url', models.URLField(blank=True, null=True, verbose_name='thumbnail URL')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (seconds)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_details', to='messaging.message')),
            ],
            options={
                'verbose_name': 'message attachment',
                'verbose_name_plural': 'message attachments',
                'db_table': 'message_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReadStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='messaging.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message read status',
                'verbose_name_plural': 'message read statuses',
                'db_table': 'message_read_status',
                'ordering': ['-read_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.ManyToManyField(related_name='read_messages', through='messaging.MessageReadStatus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'typing indicator',
                'verbose_name_plural': 'typing indicators',
                'db_table': 'typing_indicators',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', '-last_message_at'], name='conversatio_convers_8ea8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['content_type', 'object_id'], name='conversatio_content_d5b00f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='messages_convers_38b855_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='messages_sender__7375e3_idx'),
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['conversation', '-started_at'], name='typing_indi_convers_2b4caa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typingindicator',
            unique_together={('conversation', 'user')},
        ),
    ]
