# Generated by Django 5.2.9 on 2025-12-07 18:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='avatar URL')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='gender')),
                ('role', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('EMPLOYER', 'Employer'), ('ADMIN', 'Admin'), ('STAFF', 'Staff')], db_index=True, default='CANDIDATE', max_length=20, verbose_name='role')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='province')),
                ('country', models.CharField(default='Vietnam', max_length=100, verbose_name='country')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('email_verified', models.BooleanField(default=False, verbose_name='email verified')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='phone verified')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('linkedin_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='last login at')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='last login IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(blank=True, max_length=255, verbose_name='professional headline')),
                ('summary', models.TextField(blank=True, verbose_name='professional summary')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='years of experience')),
                ('current_position', models.CharField(blank=True, max_length=255, verbose_name='current position')),
                ('current_company', models.CharField(blank=True, max_length=255, verbose_name='current company')),
                ('desired_job_title', models.CharField(blank=True, max_length=255, verbose_name='desired job title')),
                ('desired_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='desired salary min')),
                ('desired_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='desired salary max')),
                ('desired_locations', models.JSONField(blank=True, default=list, verbose_name='desired locations')),
                ('job_search_status', models.CharField(choices=[('ACTIVELY_LOOKING', 'Actively Looking'), ('OPEN_TO_OFFERS', 'Open to Offers'), ('NOT_LOOKING', 'Not Looking')], default='OPEN_TO_OFFERS', max_length=20, verbose_name='job search status')),
                ('resume_url', models.URLField(blank=True, null=True, verbose_name='resume URL')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='portfolio URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('profile_completeness', models.PositiveIntegerField(default=0, verbose_name='profile completeness %')),
                ('is_public', models.BooleanField(default=True, verbose_name='public profile')),
                ('allow_employer_contact', models.BooleanField(default=True, verbose_name='allow employer contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidate profile',
                'verbose_name_plural': 'candidate profiles',
                'db_table': 'candidate_profiles',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('position', models.CharField(max_length=255, verbose_name='position in company')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='department')),
                ('business_email', models.EmailField(blank=True, max_length=254, verbose_name='business email')),
                ('business_phone', models.CharField(blank=True, max_length=15, verbose_name='business phone')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified employer')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('can_post_jobs', models.BooleanField(default=True, verbose_name='can post jobs')),
                ('can_view_candidates', models.BooleanField(default=True, verbose_name='can view candidates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employer profile',
                'verbose_name_plural': 'employer profiles',
                'db_table': 'employer_profiles',
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_resets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'role'], name='users_email_7645ab_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
    ]
