# Generated by Django 5.2.9 on 2025-12-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID for recurring billing', max_length=255, null=True, unique=True, verbose_name='Stripe customer ID'),
        ),
    ]
