# Generated by Django 5.2.9 on 2025-12-08 07:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_interview_calendar_event_id_interview_host_link_and_more'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(db_index=True, help_text='Unique code for tracking (e.g., HH-JOB123-CAND456)', max_length=20, unique=True, verbose_name='referral code')),
                ('agreed_commission_rate', models.DecimalField(decimal_places=2, help_text='Specific rate for this referral', max_digits=5, verbose_name='agreed commission rate (%)')),
                ('estimated_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Based on job salary range', max_digits=10, verbose_name='estimated commission')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SUBMITTED', 'Submitted to Employer'), ('INTERVIEWING', 'In Interview Process'), ('OFFERED', 'Offer Made'), ('HIRED', 'Candidate Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn by Headhunter')], db_index=True, default='PENDING', max_length=20, verbose_name='status')),
                ('headhunter_note', models.TextField(blank=True, help_text='Why this candidate is a good fit', verbose_name='headhunter note')),
                ('employer_feedback', models.TextField(blank=True, verbose_name='employer feedback')),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('hired_at', models.DateTimeField(blank=True, null=True, verbose_name='hired at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('headhunter', models.ForeignKey(limit_choices_to={'role': 'HEADHUNTER'}, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headhunter_referrals', to='jobs.job')),
            ],
            options={
                'verbose_name': 'candidate referral',
                'verbose_name_plural': 'candidate referrals',
                'db_table': 'candidate_referrals',
                'ordering': ['-referred_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='commission amount')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='currency')),
                ('payment_type', models.CharField(choices=[('UPFRONT', 'Upfront (upon hire)'), ('SPLIT', 'Split payment'), ('MILESTONE', 'Milestone based'), ('PROBATION_END', 'After probation period')], default='PROBATION_END', max_length=20, verbose_name='payment type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending (candidate not hired yet)'), ('APPROVED', 'Approved for payment'), ('PAID', 'Paid'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='status')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='invoice number')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='invoice date')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='paid amount')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('payment_method', models.CharField(blank=True, help_text='Bank transfer, PayPal, etc.', max_length=50, verbose_name='payment method')),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100, verbose_name='payment reference')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('dispute_reason', models.TextField(blank=True, verbose_name='dispute reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headhunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_earned', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='headhunters.candidatereferral')),
            ],
            options={
                'verbose_name': 'commission',
                'verbose_name_plural': 'commissions',
                'db_table': 'commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeadhunterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, help_text='Recruitment agency or personal brand name', max_length=255, verbose_name='company/agency name')),
                ('license_number', models.CharField(blank=True, help_text='Official recruitment license (if applicable)', max_length=100, verbose_name='business license number')),
                ('tax_code', models.CharField(blank=True, max_length=50, verbose_name='tax code')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Default commission percentage (e.g., 15.00 for 15%)', max_digits=5, verbose_name='default commission rate (%)')),
                ('commission_type', models.CharField(choices=[('PERCENTAGE', 'Percentage of first month salary'), ('FIXED', 'Fixed amount per placement'), ('TIERED', 'Tiered based on salary range')], default='PERCENTAGE', max_length=20, verbose_name='commission type')),
                ('total_referrals', models.PositiveIntegerField(default=0, help_text='Total candidates referred', verbose_name='total referrals')),
                ('successful_placements', models.PositiveIntegerField(default=0, help_text='Candidates who got hired', verbose_name='successful placements')),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total commission earned')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average rating from employers (0-5)', max_digits=3, verbose_name='average rating')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin after document check', verbose_name='verified headhunter')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('specializations', models.JSONField(blank=True, default=list, help_text='Industries/roles specialized in (e.g., ["IT", "Finance"])', verbose_name='specializations')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='bank name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='account number')),
                ('bank_account_holder', models.CharField(blank=True, max_length=255, verbose_name='account holder name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('suspended_until', models.DateTimeField(blank=True, help_text='Temporary suspension date (if violated policies)', null=True, verbose_name='suspended until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='headhunter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'headhunter profile',
                'verbose_name_plural': 'headhunter profiles',
                'db_table': 'headhunter_profiles',
            },
        ),
        migrations.CreateModel(
            name='HeadhunterRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5 stars', verbose_name='rating')),
                ('candidate_quality', models.PositiveSmallIntegerField(help_text='1-5: How well matched was the candidate?', verbose_name='candidate quality')),
                ('communication', models.PositiveSmallIntegerField(help_text='1-5: Response time and clarity', verbose_name='communication')),
                ('professionalism', models.PositiveSmallIntegerField(help_text='1-5: Professional conduct', verbose_name='professionalism')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headhunter_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('headhunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='headhunters.candidatereferral')),
            ],
            options={
                'verbose_name': 'headhunter rating',
                'verbose_name_plural': 'headhunter ratings',
                'db_table': 'headhunter_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidatereferral',
            index=models.Index(fields=['headhunter', '-referred_at'], name='candidate_r_headhun_3d5b93_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatereferral',
            index=models.Index(fields=['status', '-referred_at'], name='candidate_r_status_6fc283_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatereferral',
            index=models.Index(fields=['referral_code'], name='candidate_r_referra_0054ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatereferral',
            unique_together={('headhunter', 'candidate', 'job')},
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['headhunter', '-created_at'], name='commissions_headhun_642e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status', '-created_at'], name='commissions_status_d304e2_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['invoice_number'], name='commissions_invoice_63b51e_idx'),
        ),
        migrations.AddIndex(
            model_name='headhunterprofile',
            index=models.Index(fields=['is_verified', 'is_active'], name='headhunter__is_veri_cbc1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='headhunterprofile',
            index=models.Index(fields=['-total_commission_earned'], name='headhunter__total_c_6a5c00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='headhunterrating',
            unique_together={('employer', 'referral')},
        ),
    ]
