# Generated by Django 5.2.9 on 2025-12-07 18:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='job title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='job description')),
                ('requirements', models.TextField(verbose_name='job requirements')),
                ('benefits', models.TextField(blank=True, verbose_name='benefits')),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('TEMPORARY', 'Temporary')], default='FULL_TIME', max_length=20, verbose_name='job type')),
                ('experience_level', models.CharField(choices=[('INTERN', 'Internship'), ('ENTRY', 'Entry Level'), ('JUNIOR', 'Junior (1-3 years)'), ('MIDDLE', 'Middle (3-5 years)'), ('SENIOR', 'Senior (5-10 years)'), ('LEAD', 'Lead (10+ years)'), ('EXECUTIVE', 'Executive')], max_length=20, verbose_name='experience level')),
                ('is_remote', models.BooleanField(default=False, verbose_name='remote work')),
                ('location_city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('location_province', models.CharField(blank=True, max_length=100, verbose_name='province')),
                ('location_country', models.CharField(default='Vietnam', max_length=100, verbose_name='country')),
                ('location_address', models.TextField(blank=True, verbose_name='full address')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='min salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='max salary')),
                ('salary_currency', models.CharField(default='VND', max_length=3, verbose_name='currency')),
                ('salary_period', models.CharField(choices=[('HOURLY', 'Per Hour'), ('DAILY', 'Per Day'), ('MONTHLY', 'Per Month'), ('YEARLY', 'Per Year')], default='MONTHLY', max_length=20, verbose_name='salary period')),
                ('show_salary', models.BooleanField(default=True, verbose_name='show salary publicly')),
                ('min_years_experience', models.PositiveIntegerField(default=0, verbose_name='min years experience')),
                ('max_years_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='max years experience')),
                ('education_level', models.CharField(choices=[('HIGH_SCHOOL', 'High School'), ('VOCATIONAL', 'Vocational'), ('ASSOCIATE', 'Associate Degree'), ('BACHELOR', 'Bachelor Degree'), ('MASTER', 'Master Degree'), ('DOCTORATE', 'Doctorate'), ('ANY', 'Any')], default='ANY', max_length=50, verbose_name='education level')),
                ('application_deadline', models.DateTimeField(blank=True, null=True, verbose_name='application deadline')),
                ('num_positions', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of positions')),
                ('apply_via_platform', models.BooleanField(default=True, verbose_name='apply via platform')),
                ('external_apply_url', models.URLField(blank=True, null=True, verbose_name='external application URL')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='contact email')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured job')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='urgent hiring')),
                ('is_hot', models.BooleanField(default=False, verbose_name='hot job')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('application_count', models.PositiveIntegerField(default=0, verbose_name='application count')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='share count')),
                ('save_count', models.PositiveIntegerField(default=0, verbose_name='save count')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='master_data.jobcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='question')),
                ('question_type', models.CharField(choices=[('TEXT', 'Text Answer'), ('YES_NO', 'Yes/No'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('FILE', 'File Upload')], default='TEXT', max_length=20, verbose_name='question type')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='answer choices')),
                ('is_required', models.BooleanField(default=False, verbose_name='required')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_questions', to='jobs.job')),
            ],
            options={
                'verbose_name': 'job question',
                'verbose_name_plural': 'job questions',
                'db_table': 'job_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20, verbose_name='required level')),
                ('is_required', models.BooleanField(default=True, verbose_name='required skill')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='master_data.skill')),
            ],
            options={
                'verbose_name': 'job skill',
                'verbose_name_plural': 'job skills',
                'db_table': 'job_skills',
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobSkill', to='master_data.skill'),
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('referrer', models.URLField(blank=True, null=True, verbose_name='referrer')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='jobs.job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['slug'], name='jobs_slug_874285_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'published_at'], name='jobs_status_697456_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status'], name='jobs_company_0582d9_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_featured', 'is_hot', 'is_urgent'], name='jobs_is_feat_6a9386_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobs_created_7c32a5_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['job', 'viewed_at'], name='job_views_job_id_994b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobview',
            index=models.Index(fields=['user', 'viewed_at'], name='job_views_user_id_2dd5a6_idx'),
        ),
    ]
