# Generated by Django 5.2.9 on 2025-12-07 18:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='company name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='tagline')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('size', models.CharField(blank=True, choices=[('STARTUP', 'Startup (1-50)'), ('SMALL', 'Small (51-200)'), ('MEDIUM', 'Medium (201-1000)'), ('LARGE', 'Large (1001-5000)'), ('ENTERPRISE', 'Enterprise (5000+)')], max_length=20, verbose_name='company size')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='founded year')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='province')),
                ('country', models.CharField(default='Vietnam', max_length=100, verbose_name='country')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='company logo')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='cover image')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('total_jobs', models.PositiveIntegerField(default=0, verbose_name='total jobs posted')),
                ('active_jobs', models.PositiveIntegerField(default=0, verbose_name='active jobs')),
                ('total_employees', models.PositiveIntegerField(blank=True, null=True, verbose_name='total employees')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='master_data.industry')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFollower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify_new_jobs', models.BooleanField(default=True, verbose_name='notify on new jobs')),
                ('notify_company_updates', models.BooleanField(default=True, verbose_name='notify on company updates')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company follower',
                'verbose_name_plural': 'company followers',
                'db_table': 'company_followers',
                'ordering': ['-followed_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter'), ('MEMBER', 'Member')], default='MEMBER', max_length=50, verbose_name='role')),
                ('can_post_jobs', models.BooleanField(default=True, verbose_name='can post jobs')),
                ('can_manage_jobs', models.BooleanField(default=True, verbose_name='can manage jobs')),
                ('can_view_applications', models.BooleanField(default=True, verbose_name='can view applications')),
                ('can_manage_members', models.BooleanField(default=False, verbose_name='can manage members')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='left at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company member',
                'verbose_name_plural': 'company members',
                'db_table': 'company_members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='review title')),
                ('review_text', models.TextField(verbose_name='review text')),
                ('overall_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='overall rating')),
                ('work_life_balance', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='work-life balance')),
                ('salary_benefits', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='salary & benefits')),
                ('culture', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='company culture')),
                ('career_opportunities', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='career opportunities')),
                ('management', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='management')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='position')),
                ('employment_status', models.CharField(choices=[('CURRENT', 'Current Employee'), ('FORMER', 'Former Employee'), ('CANDIDATE', 'Candidate')], max_length=20, verbose_name='employment status')),
                ('pros', models.TextField(blank=True, verbose_name='pros')),
                ('cons', models.TextField(blank=True, verbose_name='cons')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified review')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='helpful count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'company review',
                'verbose_name_plural': 'company reviews',
                'db_table': 'company_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='companies_slug_e0676c_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_verified', 'is_active'], name='companies_is_veri_1e086a_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='companies_created_c84a3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyfollower',
            unique_together={('company', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='companymember',
            unique_together={('company', 'user')},
        ),
        migrations.AddIndex(
            model_name='companyreview',
            index=models.Index(fields=['company', 'is_approved'], name='company_rev_company_cfa162_idx'),
        ),
        migrations.AddIndex(
            model_name='companyreview',
            index=models.Index(fields=['overall_rating'], name='company_rev_overall_7448b3_idx'),
        ),
    ]
