# Generated by Django 5.2.9 on 2025-12-07 18:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(blank=True, verbose_name='cover letter')),
                ('resume_url', models.URLField(blank=True, null=True, verbose_name='resume URL')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='portfolio URL')),
                ('candidate_email', models.EmailField(max_length=254, verbose_name='candidate email')),
                ('candidate_phone', models.CharField(blank=True, max_length=15, verbose_name='candidate phone')),
                ('candidate_name', models.CharField(max_length=255, verbose_name='candidate name')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='expected salary')),
                ('expected_salary_currency', models.CharField(default='VND', max_length=3, verbose_name='currency')),
                ('available_from', models.DateField(blank=True, null=True, verbose_name='available from')),
                ('notice_period_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='notice period (days)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWING', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWING', 'Interviewing'), ('OFFERED', 'Offer Extended'), ('ACCEPTED', 'Offer Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('recruiter_rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='recruiter rating (1-5)')),
                ('ai_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='AI match score')),
                ('skill_match_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='skill match %')),
                ('screening_answers', models.JSONField(blank=True, default=dict, verbose_name='screening answers')),
                ('source', models.CharField(choices=[('PLATFORM', 'Platform'), ('EMAIL', 'Email'), ('REFERRAL', 'Referral'), ('LINKEDIN', 'LinkedIn'), ('FACEBOOK', 'Facebook'), ('OTHER', 'Other')], default='PLATFORM', max_length=50, verbose_name='application source')),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='referral code')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='viewed by recruiter')),
                ('is_starred', models.BooleanField(default=False, verbose_name='starred')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Changed'), ('NOTE_ADDED', 'Note Added'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('EMAIL_SENT', 'Email Sent'), ('VIEWED', 'Viewed'), ('ASSIGNED', 'Assigned'), ('RATING_CHANGED', 'Rating Changed')], max_length=50, verbose_name='activity type')),
                ('description', models.TextField(verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'application activity',
                'verbose_name_plural': 'application activities',
                'db_table': 'application_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(verbose_name='note')),
                ('is_private', models.BooleanField(default=True, verbose_name='private note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'application note',
                'verbose_name_plural': 'application notes',
                'db_table': 'application_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='stage name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('send_email_on_enter', models.BooleanField(default=False, verbose_name='send email on stage entry')),
                ('email_template', models.TextField(blank=True, verbose_name='email template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'application stage',
                'verbose_name_plural': 'application stages',
                'db_table': 'application_stages',
                'ordering': ['company', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='interview title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('interview_type', models.CharField(choices=[('PHONE', 'Phone Screen'), ('VIDEO', 'Video Call'), ('ONSITE', 'On-site'), ('TECHNICAL', 'Technical'), ('HR', 'HR Round'), ('FINAL', 'Final Round')], max_length=20, verbose_name='type')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled at')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='duration (minutes)')),
                ('location', models.TextField(blank=True, verbose_name='location')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='meeting link')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20, verbose_name='status')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='rating (1-5)')),
                ('recommendation', models.CharField(blank=True, choices=[('STRONG_YES', 'Strong Yes'), ('YES', 'Yes'), ('MAYBE', 'Maybe'), ('NO', 'No'), ('STRONG_NO', 'Strong No')], max_length=20, null=True, verbose_name='recommendation')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='reminder sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'interview',
                'verbose_name_plural': 'interviews',
                'db_table': 'interviews',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
