# Generated by Django 5.2.9 on 2025-12-07 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('companies', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='applicationactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationactivity',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_stages', to='companies.company'),
        ),
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.applicationstage'),
        ),
        migrations.AddField(
            model_name='interview',
            name='additional_interviewers',
            field=models.ManyToManyField(blank=True, related_name='participated_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application'),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='applicationstage',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='application_job_id_606b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', 'status'], name='application_candida_84e04d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'created_at'], name='application_status_91af05_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['assigned_to'], name='application_assigne_c164ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['application', 'status'], name='interviews_applica_436615_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['scheduled_at'], name='interviews_schedul_3fb753_idx'),
        ),
    ]
