# Generated by Django 5.2.9 on 2025-12-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='calendar_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar event ID for sync', max_length=255, null=True, verbose_name='calendar event ID'),
        ),
        migrations.AddField(
            model_name='interview',
            name='host_link',
            field=models.URLField(blank=True, null=True, verbose_name='host link'),
        ),
        migrations.AddField(
            model_name='interview',
            name='participant_link',
            field=models.URLField(blank=True, null=True, verbose_name='participant link'),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_meeting_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='meeting ID'),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='meeting password'),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_provider',
            field=models.CharField(blank=True, choices=[('JITSI', 'Jitsi Meet'), ('ZOOM', 'Zoom'), ('GOOGLE_MEET', 'Google Meet'), ('CUSTOM', 'Custom Link')], max_length=20, null=True, verbose_name='video provider'),
        ),
    ]
