# Generated by Django 5.2.9 on 2025-12-08 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_interview_calendar_event_id_interview_host_link_and_more'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., "Standard Tech Recruitment", "Executive Hiring"', max_length=200, verbose_name='pipeline name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as default for new jobs', verbose_name='default pipeline')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'application pipeline',
                'verbose_name_plural': 'application pipelines',
                'db_table': 'application_pipelines',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KanbanStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., "Phone Screening", "Technical Interview"', max_length=100, verbose_name='stage name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('stage_type', models.CharField(choices=[('NEW', 'New Applications'), ('SCREENING', 'Screening/Review'), ('ASSESSMENT', 'Assessment/Test'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer/Negotiation'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('CUSTOM', 'Custom Stage')], default='CUSTOM', max_length=20, verbose_name='stage type')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first', verbose_name='display order')),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for Kanban column', max_length=7, verbose_name='color')),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g., "user-check", "phone")', max_length=50, verbose_name='icon')),
                ('auto_send_email', models.BooleanField(default=False, help_text='Send automated email when candidate enters this stage', verbose_name='auto send email')),
                ('email_template', models.CharField(blank=True, help_text='Template ID for automated email', max_length=100, verbose_name='email template')),
                ('sla_hours', models.PositiveIntegerField(blank=True, help_text='Expected time to process candidates in this stage', null=True, verbose_name='SLA (hours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='applications.applicationpipeline')),
            ],
            options={
                'verbose_name': 'kanban stage',
                'verbose_name_plural': 'kanban stages',
                'db_table': 'kanban_stages',
                'ordering': ['pipeline', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KanbanView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., "My High Priority Candidates", "This Week\'s Applications"', max_length=100, verbose_name='view name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('filters', models.JSONField(default=dict, help_text='Saved filter criteria (e.g., {"rating__gte": 4, "is_starred": true})', verbose_name='filters')),
                ('columns_to_show', models.JSONField(blank=True, default=list, help_text='List of stage IDs to display (for focused view)', verbose_name='columns to show')),
                ('sort_order', models.CharField(default='-submitted_at', help_text='Django ORM ordering parameter', max_length=50, verbose_name='sort order')),
                ('is_shared', models.BooleanField(default=False, verbose_name='shared with team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='applications.applicationpipeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'kanban view',
                'verbose_name_plural': 'kanban views',
                'db_table': 'kanban_views',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('applications_entered', models.PositiveIntegerField(default=0, help_text='Number of applications that entered this stage', verbose_name='applications entered')),
                ('applications_exited', models.PositiveIntegerField(default=0, help_text='Number that moved to next stage', verbose_name='applications exited')),
                ('applications_stuck', models.PositiveIntegerField(default=0, help_text='Exceeded SLA without moving', verbose_name='applications stuck')),
                ('avg_time_in_stage_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='avg time in stage (hours)')),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, help_text='% that progressed to next stage', max_digits=5, null=True, verbose_name='conversion rate (%)')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='applications.applicationpipeline')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='applications.kanbanstage')),
            ],
            options={
                'verbose_name': 'pipeline metrics',
                'verbose_name_plural': 'pipeline metrics',
                'db_table': 'pipeline_metrics',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, help_text='Optional note explaining why moved', verbose_name='reason for transition')),
                ('time_in_previous_stage', models.DurationField(blank=True, help_text='How long candidate spent in previous stage', null=True, verbose_name='time in previous stage')),
                ('transitioned_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='applications.application')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_from', to='applications.kanbanstage')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_transitions_performed', to=settings.AUTH_USER_MODEL)),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='applications.kanbanstage')),
            ],
            options={
                'verbose_name': 'stage transition',
                'verbose_name_plural': 'stage transitions',
                'db_table': 'stage_transitions',
                'ordering': ['-transitioned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kanbanstage',
            index=models.Index(fields=['pipeline', 'order'], name='kanban_stag_pipelin_e2563d_idx'),
        ),
        migrations.AddIndex(
            model_name='kanbanstage',
            index=models.Index(fields=['stage_type'], name='kanban_stag_stage_t_4f824d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kanbanstage',
            unique_together={('pipeline', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='kanbanview',
            unique_together={('user', 'pipeline', 'name')},
        ),
        migrations.AddIndex(
            model_name='pipelinemetrics',
            index=models.Index(fields=['pipeline', '-period_end'], name='pipeline_me_pipelin_b2aece_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinemetrics',
            index=models.Index(fields=['stage', '-period_end'], name='pipeline_me_stage_i_08bb34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinemetrics',
            unique_together={('pipeline', 'stage', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='stagetransition',
            index=models.Index(fields=['application', '-transitioned_at'], name='stage_trans_applica_3f7646_idx'),
        ),
        migrations.AddIndex(
            model_name='stagetransition',
            index=models.Index(fields=['to_stage', '-transitioned_at'], name='stage_trans_to_stag_c579ac_idx'),
        ),
    ]
