# Generated by Django 5.2.9 on 2025-12-07 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='search name')),
                ('query', models.CharField(blank=True, max_length=500, verbose_name='search query')),
                ('search_type', models.CharField(choices=[('JOB', 'Job Search'), ('COMPANY', 'Company Search')], default='JOB', max_length=20, verbose_name='search type')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filters')),
                ('email_alerts', models.BooleanField(default=True, verbose_name='email alerts')),
                ('alert_frequency', models.CharField(choices=[('INSTANT', 'Instant'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=20, verbose_name='alert frequency')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True, verbose_name='last alerted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saved search',
                'verbose_name_plural': 'saved searches',
                'db_table': 'saved_searches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='saved_searc_user_id_2b1034_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500, verbose_name='search query')),
                ('search_type', models.CharField(choices=[('JOB', 'Job Search'), ('COMPANY', 'Company Search'), ('CANDIDATE', 'Candidate Search')], default='JOB', max_length=20, verbose_name='search type')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='filters')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='results count')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='session ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'search history',
                'verbose_name_plural': 'search histories',
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='search_hist_user_id_3ea0ad_idx'), models.Index(fields=['search_type', '-created_at'], name='search_hist_search__d46f38_idx')],
            },
        ),
    ]
