# Generated by Django 5.2.9 on 2025-12-07 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='package name')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='package code')),
                ('description', models.TextField(verbose_name='description')),
                ('package_type', models.CharField(choices=[('JOB_POSTING', 'Job Posting'), ('FEATURED_JOB', 'Featured Job'), ('URGENT_JOB', 'Urgent Job'), ('PREMIUM_ACCOUNT', 'Premium Account'), ('CV_DATABASE', 'CV Database Access'), ('CANDIDATE_SEARCH', 'Candidate Search'), ('COMPANY_BRANDING', 'Company Branding')], max_length=50, verbose_name='package type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='currency')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount price')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='duration (days)')),
                ('job_posts_quota', models.PositiveIntegerField(default=0, help_text='0 = unlimited', verbose_name='job posts quota')),
                ('featured_quota', models.PositiveIntegerField(default=0, verbose_name='featured quota')),
                ('urgent_quota', models.PositiveIntegerField(default=0, verbose_name='urgent quota')),
                ('cv_views_quota', models.PositiveIntegerField(default=0, verbose_name='CV views quota')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='features')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_popular', models.BooleanField(default=False, verbose_name='popular')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'payment package',
                'verbose_name_plural': 'payment packages',
                'db_table': 'payment_packages',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='order ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='currency')),
                ('payment_method', models.CharField(choices=[('VNPAY', 'VNPay'), ('STRIPE', 'Stripe'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20, verbose_name='status')),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='transaction ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='gateway response')),
                ('bank_code', models.CharField(blank=True, max_length=50, verbose_name='bank code')),
                ('card_type', models.CharField(blank=True, max_length=50, verbose_name='card type')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentpackage')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='invoice number')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='issue date')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='buyer name')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='buyer email')),
                ('buyer_phone', models.CharField(blank=True, max_length=20, verbose_name='buyer phone')),
                ('buyer_address', models.TextField(blank=True, verbose_name='buyer address')),
                ('buyer_tax_code', models.CharField(blank=True, max_length=50, verbose_name='buyer tax code')),
                ('items', models.JSONField(default=list, verbose_name='items')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='tax amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total amount')),
                ('is_sent', models.BooleanField(default=False, verbose_name='sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payments.payment')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('VNPAY', 'VNPay'), ('STRIPE', 'Stripe')], max_length=20, verbose_name='gateway')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP method')),
                ('path', models.CharField(max_length=255, verbose_name='path')),
                ('headers', models.JSONField(default=dict, verbose_name='headers')),
                ('query_params', models.JSONField(default=dict, verbose_name='query params')),
                ('body', models.JSONField(blank=True, default=dict, verbose_name='body')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='status code')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='response data')),
                ('is_processed', models.BooleanField(default=False, verbose_name='processed')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.payment')),
            ],
            options={
                'verbose_name': 'payment webhook',
                'verbose_name_plural': 'payment webhooks',
                'db_table': 'payment_webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('job_posts_remaining', models.PositiveIntegerField(default=0, verbose_name='job posts remaining')),
                ('featured_remaining', models.PositiveIntegerField(default=0, verbose_name='featured remaining')),
                ('urgent_remaining', models.PositiveIntegerField(default=0, verbose_name='urgent remaining')),
                ('cv_views_remaining', models.PositiveIntegerField(default=0, verbose_name='CV views remaining')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20, verbose_name='status')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='auto renew')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.company')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.paymentpackage')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='payments_user_id_2c5fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', '-created_at'], name='payments_company_c4a95b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_status_db6b16_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status', '-end_date'], name='subscriptio_user_id_2f3ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['company', 'status', '-end_date'], name='subscriptio_company_afb8fa_idx'),
        ),
    ]
