# Generated by Django 5.2.9 on 2025-12-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID for this subscription', max_length=255, null=True, verbose_name='Stripe customer ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe subscription ID for recurring billing', max_length=255, null=True, unique=True, verbose_name='Stripe subscription ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended'), ('PAST_DUE', 'Past Due')], db_index=True, default='ACTIVE', max_length=20, verbose_name='status'),
        ),
    ]
