# Generated by Django 5.2.9 on 2025-12-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='grace_period_ends',
            field=models.DateTimeField(blank=True, help_text='End date of grace period after payment failure', null=True, verbose_name='grace period ends'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of failed payment retry attempts', verbose_name='payment retry count'),
        ),
    ]
