# Generated by Django 5.2.9 on 2025-12-08 07:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInsuranceRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_si_rate', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='BHXH - Employee contribution', max_digits=5, verbose_name='employee social insurance (%)')),
                ('employee_hi_rate', models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='BHYT - Employee contribution', max_digits=5, verbose_name='employee health insurance (%)')),
                ('employee_ui_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='BHTN - Employee contribution', max_digits=5, verbose_name='employee unemployment insurance (%)')),
                ('employer_si_rate', models.DecimalField(decimal_places=2, default=Decimal('17.5'), help_text='BHXH - Employer contribution', max_digits=5, verbose_name='employer social insurance (%)')),
                ('employer_hi_rate', models.DecimalField(decimal_places=2, default=Decimal('3.0'), help_text='BHYT - Employer contribution', max_digits=5, verbose_name='employer health insurance (%)')),
                ('employer_ui_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='BHTN - Employer contribution', max_digits=5, verbose_name='employer unemployment insurance (%)')),
                ('si_max_salary', models.DecimalField(decimal_places=2, default=Decimal('36000000'), help_text='Max monthly salary subject to SI (VND)', max_digits=12, verbose_name='max salary for SI calculation')),
                ('regional_min_wage', models.DecimalField(decimal_places=2, default=Decimal('4960000'), help_text='Base wage for region 1 (VND)', max_digits=12, verbose_name='regional minimum wage')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='effective to')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'social insurance rate',
                'verbose_name_plural': 'social insurance rates',
                'db_table': 'social_insurance_rates',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SalaryBenchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(db_index=True, max_length=200, verbose_name='job title')),
                ('industry', models.CharField(choices=[('IT', 'Information Technology'), ('FINANCE', 'Finance & Banking'), ('MARKETING', 'Marketing & Sales'), ('MANUFACTURING', 'Manufacturing'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail & E-commerce'), ('OTHER', 'Other')], max_length=100, verbose_name='industry')),
                ('experience_level', models.CharField(choices=[('INTERN', 'Intern'), ('JUNIOR', 'Junior (0-2 years)'), ('MID', 'Mid-level (2-5 years)'), ('SENIOR', 'Senior (5-10 years)'), ('LEAD', 'Lead/Manager (10+ years)')], max_length=20, verbose_name='experience level')),
                ('city', models.CharField(default='Hanoi', max_length=100, verbose_name='city')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='minimum salary')),
                ('avg_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='average salary')),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='maximum salary')),
                ('sample_size', models.PositiveIntegerField(default=0, help_text='Number of data points', verbose_name='sample size')),
                ('data_source', models.CharField(default='Platform Data', help_text='e.g., "Platform Data", "Survey", "External API"', max_length=100, verbose_name='data source')),
                ('last_updated', models.DateField(verbose_name='last updated')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'salary benchmark',
                'verbose_name_plural': 'salary benchmarks',
                'db_table': 'salary_benchmarks',
                'ordering': ['job_title', 'experience_level'],
                'indexes': [models.Index(fields=['job_title', 'city'], name='salary_benc_job_tit_8827ef_idx'), models.Index(fields=['industry', 'experience_level'], name='salary_benc_industr_fb144a_idx')],
                'unique_together': {('job_title', 'industry', 'experience_level', 'city')},
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Monthly taxable income from (VND)', max_digits=12, verbose_name='minimum amount')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly taxable income to (VND). NULL = unlimited', max_digits=12, null=True, verbose_name='maximum amount')),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Tax percentage for this bracket', max_digits=5, verbose_name='tax rate (%)')),
                ('year', models.PositiveIntegerField(default=2025, help_text='Tax year this bracket applies to', verbose_name='applicable year')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tax bracket',
                'verbose_name_plural': 'tax brackets',
                'db_table': 'tax_brackets',
                'ordering': ['year', 'min_amount'],
                'indexes': [models.Index(fields=['year', 'is_active'], name='tax_bracket_year_d82747_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalaryCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Monthly gross salary (VND)', max_digits=12, verbose_name='gross salary')),
                ('region', models.PositiveSmallIntegerField(choices=[(1, 'Region 1 (Hanoi, HCM)'), (2, 'Region 2 (Major cities)'), (3, 'Region 3 (Other cities)'), (4, 'Region 4 (Rural areas)')], default=1, help_text='For minimum wage calculation', verbose_name='region')),
                ('num_dependents', models.PositiveSmallIntegerField(default=0, help_text='For family deduction (4.4M VND per person)', verbose_name='number of dependents')),
                ('si_employee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='employee SI contribution')),
                ('hi_employee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='employee HI contribution')),
                ('ui_employee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='employee UI contribution')),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='taxable income')),
                ('personal_income_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='personal income tax')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='net salary (take-home)')),
                ('employer_si', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='employer SI cost')),
                ('employer_hi', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='employer HI cost')),
                ('employer_ui', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='employer UI cost')),
                ('total_cost_to_company', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total cost to company')),
                ('calculation_date', models.DateField(auto_now_add=True, verbose_name='calculation date')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='For analytics', null=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'salary calculation',
                'verbose_name_plural': 'salary calculations',
                'db_table': 'salary_calculations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='salary_calc_user_id_bf8f3d_idx'), models.Index(fields=['gross_salary'], name='salary_calc_gross_s_5a2a9f_idx'), models.Index(fields=['-calculation_date'], name='salary_calc_calcula_ece694_idx')],
            },
        ),
    ]
